apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${WORKSPACE_NAME}-elyra-balsam
  labels:
    app: ${WORKSPACE_NAME}-elyra-balsam
  namespace: ${PROGRAM_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${WORKSPACE_NAME}-elyra-balsam
  template:
    metadata:
      labels:
        app: ${WORKSPACE_NAME}-elyra-balsam
    spec:
      serviceAccountName: elyra-sa
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
        runAsGroup: 3000
      containers:
      - name: elyra-balsam
        image: statisticssweden/scb-elyra:0.0.1
        command: ["/bin/bash", "-c"]
        args: ["bash /usr/local/bin/start-elyra.sh --NotebookApp.token=''"]
        resources:
          requests:
            memory: "500Mi"
            cpu: "1000m"
          limits:
            memory: "1000Mi"
            cpu: "2000m"
        volumeMounts:
        - mountPath: "/home/jovyan"
          name: pdelyra
        ports:
        - containerPort: 8888
      volumes:
        - name: pdelyra
          persistentVolumeClaim:
            claimName: ${WORKSPACE_NAME}-pvc-elyra-claim
      
