apiVersion: v1
kind: Service
metadata:
  name: ${WORKSPACE_NAME}-elyra-balsam-service
  namespace: ${PROGRAM_NAME}
spec:
  type: ClusterIP
  selector:
    app: ${WORKSPACE_NAME}-elyra-balsam
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888