apiVersion: v1
kind: Service
metadata:
  name: balsam-api
  namespace: balsam-system
spec:
  type: {{ .Values.balsamApi.service.type }}
  selector:
    app: balsam-api
  ports:
    - protocol: TCP
      port: {{ .Values.balsamApi.service.port }}
      targetPort: {{ .Values.balsamApi.containerPort }}