apiVersion: v1
kind: Service
metadata:
  name: git-provider
  namespace: balsam-system
spec:
  type: {{ .Values.gitProvider.service.type }}
  selector:
    app: gitlab-provider
  ports:
    - protocol: TCP
      port: {{ .Values.gitProvider.service.port }}
      targetPort: {{ .Values.gitProvider.containerPort }}