apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitProvider.secret.name }}
  namespace: balsam-system
type: Opaque
data:
  API__PAT: {{ .Values.gitProvider.secret.data.API__PAT | b64enc }}