{{- if .Values.roleBinding.enabled -}}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: balsam-app-psp-binding
  namespace: balsam-system
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: balsam-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.roleBinding.roleRef }}

{{- end -}}