apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${WORKSPACE_NAME}-pvc-elyra-claim
  namespace: ${PROGRAM_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: tanzu-workload